{{- if .Values.setup.firewall.destination.internalKubernetesCluster.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.config.resourceName }}-float-service
spec:
{{- if and .Values.setup.firewall.enabled .Values.setup.firewall.destination.internalKubernetesCluster.enabled }}
  loadBalancerIP: "{{ .Values.config.floatLoadBalancerIP }}"
  type: LoadBalancer
{{- end }}
  selector:
    app: {{ .Values.config.resourceName }}-float
  ports:
  - name: p2p
    protocol: TCP
    port: {{ .Values.corda.node.conf.p2pPort }}
    targetPort: {{ .Values.corda.node.conf.p2pPort }}
  - name: bridge-tunnel
    protocol: TCP
    port: {{ .Values.corda.node.conf.bridgeTunnelPort }}
    targetPort: {{ .Values.corda.node.conf.bridgeTunnelPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.resourceName }}-float-deployment
  labels:
    app: {{ .Values.config.resourceName }}-float
spec:
  replicas: 1   
  selector:
    matchLabels:
      app: {{ .Values.config.resourceName }}-float
  template:
    metadata:
      labels:
        app: {{ .Values.config.resourceName }}-float
    spec:
{{- if .Values.config.storage.awsEBS.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.config.storage.node.volumeHost }}
{{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: {{ .Values.config.resourceName }}-float-pv
        persistentVolumeClaim:
          claimName: {{ .Values.config.resourceName }}-float-pvc
      - name: float-config-volume
        configMap:
          name: {{ .Values.config.resourceName }}-corda-configmap
      imagePullSecrets:
      - name: container-registry-secret
      containers:
      - name: {{ .Values.config.resourceName }}-float
        image: {{ .Values.config.containerRegistry.serverAddress }}/{{ .Values.config.dockerImageFirewall }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: {{ .Values.corda.node.conf.p2pPort }} 
        - containerPort: {{ .Values.corda.node.conf.bridgeTunnelPort }} 
        volumeMounts:
        - mountPath: /opt/corda/workspace
          name: {{ .Values.config.resourceName }}-float-pv
        - mountPath: /opt/corda/workspace/network-parameters
          name: float-config-volume
          subPath: network-parameters.file
          readOnly: true
        - mountPath: /opt/corda/workspace/ping.sh
          name: float-config-volume
          subPath: ping.sh
          readOnly: true
        - mountPath: /opt/corda/workspace/firewall.conf
          name: float-config-volume
          subPath: float.conf
          readOnly: true
        - mountPath: /opt/corda/workspace/certificates/float.jks
          name: float-config-volume
          subPath: float.jks
          readOnly: true
        - mountPath: /opt/corda/workspace/certificates/sslkeystore.jks
          name: float-config-volume
          subPath: sslkeystore.jks
          readOnly: true
        - mountPath: /opt/corda/workspace/certificates/trust.jks
          name: float-config-volume
          subPath: trust.jks
          readOnly: true
        - mountPath: /opt/corda/workspace/certificates/truststore.jks
          name: float-config-volume
          subPath: truststore.jks
          readOnly: true

{{- end }}